// PropertyDocz — Lender Questionnaire Template
// Fannie Mae Form 1076 / Freddie Mac Form 476
// Brand: XeedlyAI / PropertyDocz design system

// --- PAGE SETUP ---
#set page(
  margin: (top: 0.75in, bottom: 1in, left: 0.65in, right: 0.65in),
  numbering: "1",
  footer: context [
    #set text(font: "Inter", size: 7pt, fill: rgb("#999"))
    #line(length: 100%, stroke: 0.5pt + rgb("#E0E0E0"))
    #v(4pt)
    #grid(
      columns: (1fr, auto, 1fr),
      align(left)[Generated by PropertyDocz \| propertydocz.com],
      align(center)[Page #counter(page).display("1")],
      align(right)[Fannie Mae 1076 / Freddie Mac 476],
    )
  ],
)
#set text(font: "Inter", size: 9pt, fill: rgb("#1A1A2E"))
#set par(justify: true, leading: 0.6em)

// --- SUBTITLE BAR HELPER ---
#let field-label(body) = {
  rect(
    width: 100%,
    inset: (x: 6pt, y: 3pt),
    fill: rgb("#EEEFF2"),
    radius: 1pt,
  )[#text(weight: "bold", size: 8pt, fill: rgb("#1A1A2E"))[#body]]
}

// --- HEADER BAR ---
#rect(
  width: 100%,
  inset: (x: 16pt, y: 12pt),
  fill: rgb("#1A1A2E"),
  radius: 4pt,
)[
  #grid(
    columns: (1fr, auto),
    [
      #text(font: "Inter", size: 14pt, weight: "bold", fill: white)[HOA LENDER QUESTIONNAIRE]
      #v(2pt)
      #text(font: "Inter", size: 8pt, fill: rgb("#38b6ff"))[Fannie Mae Form 1076 / Freddie Mac Form 476]
    ],
    align(right)[
      #text(font: "Inter", size: 8pt, fill: rgb("#8899AA"))[Preparation Date]
      #v(1pt)
      #text(font: "Inter", size: 10pt, weight: "bold", fill: white)[#{preparation_date}]
    ],
  )
]

#v(10pt)

// --- SECTION 1: BASIC PROJECT INFO ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 1 #h(8pt) Basic Project Information]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[HOA/Project Name] #pad(left: 14pt, top: 2pt)[#{association_name}]],
    [#field-label[Legal Name] #pad(left: 14pt, top: 2pt)[#{association_legal_name}]],
    [#field-label[Address] #pad(left: 14pt, top: 2pt)[#{association_address}]],
    [#field-label[City, State, ZIP] #pad(left: 14pt, top: 2pt)[#{association_city}, #{association_state} #{association_zip}]],
    [#field-label[Management Company] #pad(left: 14pt, top: 2pt)[#{manager_name}]],
    [#field-label[Contact Email] #pad(left: 14pt, top: 2pt)[#{manager_email}]],
    [#field-label[Contact Phone] #pad(left: 14pt, top: 2pt)[#{manager_phone}]],
    [#field-label[Tax ID (EIN)] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono", size: 9pt)[#{association_ein}]]],
    [#field-label[Year Built] #pad(left: 14pt, top: 2pt)[#{year_built}]],
    [#field-label[Year Converted] #pad(left: 14pt, top: 2pt)[#{year_converted}]],
  )
]

#v(10pt)

// --- SECTION 2: UNIT & PROJECT COMPOSITION ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 2 #h(8pt) Unit & Project Composition]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Total Units] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{total_units}]]],
    [#field-label[Subject Unit] #pad(left: 14pt, top: 2pt)[#{unit_number}]],
    [#field-label[Property Address] #pad(left: 14pt, top: 2pt)[#{property_address}]],
    [#field-label[Owner of Record] #pad(left: 14pt, top: 2pt)[#{owner_name}]],
    [#field-label[Phases Complete] #pad(left: 14pt, top: 2pt)[#{phases_complete}]],
    [#field-label[Additional Phases Planned] #pad(left: 14pt, top: 2pt)[#{additional_phases_planned}]],
  )
]

#v(10pt)

// --- SECTION 3: PROJECT COMPLETION & CONTROL ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 3 #h(8pt) Project Completion & Control]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Project complete?] #pad(left: 14pt, top: 2pt)[#{project_complete}]],
    [#field-label[% Complete] #pad(left: 14pt, top: 2pt)[#{percent_complete}]],
    [#field-label[Developer still in control?] #pad(left: 14pt, top: 2pt)[#{developer_in_control}]],
    [#field-label[Turnover date] #pad(left: 14pt, top: 2pt)[#{turnover_date}]],
    [#field-label[Pending additions/annexations?] #pad(left: 14pt, top: 2pt)[#{pending_annexations}]],
    [#field-label[Conversion project?] #pad(left: 14pt, top: 2pt)[#{is_conversion}]],
  )
]

#v(10pt)

// --- SECTION 4: OWNERSHIP DISTRIBUTION ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 4 #h(8pt) Ownership Distribution]
  ]
  #v(6pt)

  #table(
    columns: (1fr, auto),
    stroke: none,
    inset: (x: 10pt, y: 5pt),
    fill: (_, y) => if calc.rem(y, 2) == 0 { rgb("#F4F5F7") } else { white },
    table.header(
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Category]],
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Count / %]],
    ),
    [Total Units], [#text(font: "JetBrains Mono", size: 9pt)[#{total_units}]],
    [Owner-Occupied Units], [#text(font: "JetBrains Mono", size: 9pt)[#{owner_occupied_units}]],
    [Investor-Owned / Rented], [#text(font: "JetBrains Mono", size: 9pt)[#{investor_owned_units}]],
    [% Owner-Occupied], [#text(font: "JetBrains Mono", size: 9pt)[#{percent_owner_occupied}]],
    [Units Owned by Single Entity], [#text(font: "JetBrains Mono", size: 9pt)[#{units_single_entity}]],
    [% Owned by Single Entity], [#text(font: "JetBrains Mono", size: 9pt)[#{percent_single_entity}]],
    [Developer-Held Units], [#text(font: "JetBrains Mono", size: 9pt)[#{developer_held_units}]],
    [Delinquent Units (60+ days)], [#text(font: "JetBrains Mono", size: 9pt)[#{delinquent_units}]],
    [% Delinquent (60+ days)], [#text(font: "JetBrains Mono", size: 9pt)[#{percent_delinquent}]],
  )
]

#v(10pt)

// --- SECTION 5: FINANCIAL ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 5 #h(8pt) Financial Information]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Annual Operating Budget] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{annual_budget}]]],
    [#field-label[Monthly Assessment] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{monthly_assessment}]]],
    [#field-label[Assessment Frequency] #pad(left: 14pt, top: 2pt)[#{assessment_frequency}]],
    [#field-label[Special assessments?] #pad(left: 14pt, top: 2pt)[#{special_assessments_planned}]],
    [#field-label[Special Assessment Details] #pad(left: 14pt, top: 2pt)[#{special_assessment_details}]],
    [#field-label[Assessments adequate?] #pad(left: 14pt, top: 2pt)[#{assessments_adequate}]],
  )
]

#v(10pt)

// --- SECTION 6: RESERVES ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 6 #h(8pt) Reserve Fund]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Current Reserve Balance] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{reserve_balance}]]],
    [#field-label[Percent Funded] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{percent_funded}]]],
    [#field-label[Reserve Study Completed?] #pad(left: 14pt, top: 2pt)[#{reserve_study_completed}]],
    [#field-label[Reserve Study Date] #pad(left: 14pt, top: 2pt)[#{reserve_study_date}]],
    [#field-label[Study current (within 3 yrs)?] #pad(left: 14pt, top: 2pt)[#{reserve_study_current}]],
    [#field-label[Annual Reserve Contribution] #pad(left: 14pt, top: 2pt)[#text(font: "JetBrains Mono")[#{annual_reserve_contribution}]]],
  )
]

#v(10pt)

// --- SECTION 7: INSURANCE ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 7 #h(8pt) Insurance]
  ]
  #v(6pt)

  #table(
    columns: (1fr, auto, auto),
    stroke: none,
    inset: (x: 8pt, y: 5pt),
    fill: (_, y) => if calc.rem(y, 2) == 0 { rgb("#F4F5F7") } else { white },
    table.header(
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Coverage Type]],
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Carrier / Details]],
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Expiration]],
    ),
    [Master/Hazard Policy], [#{master_policy_carrier}], [#{master_policy_expiration}],
    [General Liability], [#{general_liability}], [#{general_liability_expiration}],
    [Fidelity Bond / Crime], [#{fidelity_bond}], [#{fidelity_bond_expiration}],
    [Flood Insurance], [#{flood_insurance}], [#{flood_insurance_expiration}],
    [Workers' Compensation], [#{workers_comp}], [#{workers_comp_expiration}],
    [Umbrella / Excess], [#{umbrella_coverage}], [#{umbrella_expiration}],
  )

  #v(5pt)
  #field-label[Flood Zone]
  #pad(left: 14pt, top: 2pt)[#{flood_zone}]
]

#v(10pt)

// --- SECTION 8: LITIGATION ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 8 #h(8pt) Litigation]
  ]
  #v(6pt)

  #stack(dir: ttb, spacing: 5pt,
    field-label[Current litigation?],
    pad(left: 14pt)[#{in_litigation}],
    field-label[Nature of litigation],
    pad(left: 14pt)[#{litigation_details}],
    field-label[Safety/structural related?],
    pad(left: 14pt)[#{litigation_safety_related}],
  )
]

#v(10pt)

// --- SECTION 9: RESTRICTIONS ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 9 #h(8pt) Restrictions & Policies]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Rental Restrictions?] #pad(left: 14pt, top: 2pt)[#{rental_policy}]],
    [#field-label[Short-Term Rental?] #pad(left: 14pt, top: 2pt)[#{short_term_rental_policy}]],
    [#field-label[Rental Cap] #pad(left: 14pt, top: 2pt)[#{rental_cap}]],
    [#field-label[Right of First Refusal?] #pad(left: 14pt, top: 2pt)[#{right_of_first_refusal}]],
    [#field-label[Age Restrictions?] #pad(left: 14pt, top: 2pt)[#{age_restrictions}]],
    [#field-label[Pet Restrictions?] #pad(left: 14pt, top: 2pt)[#{pet_policy}]],
    [#field-label[Mandatory Fees?] #pad(left: 14pt, top: 2pt)[#{mandatory_membership_fees}]],
    [#field-label[Commercial Space?] #pad(left: 14pt, top: 2pt)[#{commercial_space}]],
  )
]

#v(10pt)

// --- SECTION 10: ENVIRONMENTAL & SAFETY ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 10 #h(8pt) Environmental & Safety]
  ]
  #v(6pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 5pt,
    column-gutter: 14pt,
    [#field-label[Environmental hazards?] #pad(left: 14pt, top: 2pt)[#{environmental_hazards}]],
    [#field-label[Asbestos?] #pad(left: 14pt, top: 2pt)[#{asbestos}]],
    [#field-label[Lead-based paint?] #pad(left: 14pt, top: 2pt)[#{lead_paint}]],
    [#field-label[Mold issues?] #pad(left: 14pt, top: 2pt)[#{mold_issues}]],
    [#field-label[FEMA disaster area?] #pad(left: 14pt, top: 2pt)[#{fema_disaster}]],
    [#field-label[Structural deficiencies?] #pad(left: 14pt, top: 2pt)[#{structural_deficiencies}]],
    [#field-label[Deferred maintenance?] #pad(left: 14pt, top: 2pt)[#{deferred_maintenance}]],
    [#field-label[Failed inspections?] #pad(left: 14pt, top: 2pt)[#{failed_inspections}]],
  )
]

#v(10pt)

// --- SECTION 11: COMMON AREA & SERVICES ---
#block(breakable: false)[
  #rect(width: 100%, inset: (x: 10pt, y: 5pt), fill: rgb("#1A1A2E"), radius: 2pt)[
    #text(font: "Inter", size: 8.5pt, weight: "bold", fill: white)[Section 11 #h(8pt) Common Area & Services]
  ]
  #v(6pt)

  #stack(dir: ttb, spacing: 5pt,
    field-label[Common amenities],
    pad(left: 14pt)[#{common_amenities}],
    field-label[Utilities included],
    pad(left: 14pt)[#{utilities_included}],
    field-label[FHA approved?],
    pad(left: 14pt)[#{fha_approved}],
    field-label[VA approved?],
    pad(left: 14pt)[#{va_approved}],
  )
]

#v(14pt)

// --- CERTIFICATION ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: 10pt,
    fill: rgb("#F0F7FF"),
    stroke: (left: 3pt + rgb("#38b6ff")),
    radius: 2pt,
  )[
    #text(size: 8pt, fill: rgb("#333"))[
      *CERTIFICATION:* The information provided in this questionnaire is accurate to the best of our knowledge as of the preparation date. This questionnaire is provided for mortgage lending due diligence purposes and is not a guarantee or warranty of any kind.

      #v(3pt)
      *Preparation Date:* #{preparation_date}
    ]
  ]
]

#v(18pt)

// SIGNATURE_BLOCK
