// PropertyDocz — Resale Certificate Template
// Utah Code §57-8a-227
// Brand: XeedlyAI / PropertyDocz design system

// --- PAGE SETUP ---
#set page(
  margin: (top: 0.75in, bottom: 1in, left: 0.75in, right: 0.75in),
  numbering: "1",
  footer: context [
    #set text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 7pt, fill: rgb("#999"))
    #line(length: 100%, stroke: 0.5pt + rgb("#E0E0E0"))
    #v(4pt)
    #grid(
      columns: (1fr, auto, 1fr),
      align(left)[Generated by PropertyDocz \| propertydocz.com],
      align(center)[Page #counter(page).display("1")],
      align(right)[Valid for 30 days from preparation date],
    )
  ],
)
#set text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9.5pt, fill: rgb("#1A1A2E"))
#set par(justify: true, leading: 0.65em)

// --- HEADER BAR ---
#rect(
  width: 100%,
  inset: (x: 16pt, y: 12pt),
  fill: rgb("#1A1A2E"),
  radius: 4pt,
)[
  #grid(
    columns: (1fr, auto),
    [
      #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 14pt, weight: "bold", fill: white)[RESALE CERTIFICATE]
      #v(2pt)
      #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 8pt, fill: rgb("#38b6ff"))[Pursuant to Utah Code \u{00A7}57-8a-227]
    ],
    align(right)[
      #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 8pt, fill: rgb("#8899AA"))[Preparation Date]
      #v(1pt)
      #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 10pt, weight: "bold", fill: white)[#{preparation_date}]
    ],
  )
]

#v(12pt)

// --- ASSOCIATION / PROPERTY INFO (two-column) ---
#block(breakable: false)[
  #grid(
    columns: (1fr, 1fr),
    gutter: 16pt,
    [
      #text(size: 8pt, weight: "bold", fill: rgb("#38b6ff"))[ASSOCIATION]
      #v(4pt)
      #text(size: 11pt, weight: "bold")[#{association_name}]
      #v(2pt)
      #text(size: 9pt, fill: rgb("#555"))[
        #{association_address} \
        #{association_city}, #{association_state} #{association_zip}
      ]
      #v(4pt)
      #text(size: 8pt, fill: rgb("#777"))[
        Manager: #{manager_name} \
        #{manager_email} #h(6pt) #{manager_phone}
      ]
    ],
    [
      #text(size: 8pt, weight: "bold", fill: rgb("#38b6ff"))[PROPERTY]
      #v(4pt)
      #text(size: 11pt, weight: "bold")[#{property_address}]
      #v(2pt)
      #text(size: 9pt, fill: rgb("#555"))[
        Unit/Lot: #{unit_number} \
        Owner: #{owner_name}
      ]
    ],
  )
]

#v(14pt)

// --- SECTION 1: ASSESSMENT & FINANCIAL SUMMARY ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 1 #h(8pt) Assessment & Financial Summary]
  ]
  #v(8pt)

  #table(
    columns: (1fr, auto),
    stroke: none,
    inset: (x: 10pt, y: 6pt),
    fill: (_, y) => if calc.rem(y, 2) == 0 { rgb("#F4F5F7") } else { white },
    table.header(
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Item]],
      table.cell(fill: rgb("#38b6ff"))[#text(size: 8pt, weight: "bold", fill: white)[Amount]],
    ),
    [Monthly Assessment], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{monthly_assessment}]],
    [Assessment Frequency], [#{assessment_frequency}],
    [Current Balance Due], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{current_balance_due}]],
    [Special Assessments Due], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{special_assessments_due}]],
    [Transfer Fee], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{transfer_fee}]],
    [Capital Contribution], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{capital_contribution}]],
    [Other Fees Due at Closing], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{other_fees}]],
    [Prorated Assessment], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{prorated_assessment}]],
    table.cell(fill: rgb("#E8F4FD"))[#text(weight: "bold")[Total Due at Closing]],
    table.cell(fill: rgb("#E8F4FD"))[#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 10pt, weight: "bold", fill: rgb("#1A1A2E"))[#{total_due_at_closing}]],
  )
]

#v(14pt)

// --- SECTION 2: ACCOUNT STATUS ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 2 #h(8pt) Account Status]
  ]
  #v(8pt)

  #grid(
    columns: (120pt, 1fr),
    gutter: 6pt,
    [#text(weight: "bold", size: 9pt)[Status:]], [#{account_status}],
    [#text(weight: "bold", size: 9pt)[Violations:]], [#{outstanding_violations}],
  )
]

#v(14pt)

// --- SECTION 3: INSURANCE ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 3 #h(8pt) Insurance Information]
  ]
  #v(8pt)

  #grid(
    columns: (1fr, 1fr),
    gutter: 8pt,
    [#text(weight: "bold", size: 8pt)[Master Policy Carrier] #v(1pt) #text(size: 9pt)[#{master_policy_carrier}]],
    [#text(weight: "bold", size: 8pt)[Policy Expiration] #v(1pt) #text(size: 9pt)[#{master_policy_expiration}]],
    [#text(weight: "bold", size: 8pt)[General Liability] #v(1pt) #text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{general_liability}]],
    [#text(weight: "bold", size: 8pt)[Fidelity Bond] #v(1pt) #text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{fidelity_bond}]],
    [#text(weight: "bold", size: 8pt)[Flood Zone] #v(1pt) #text(size: 9pt)[#{flood_zone}]],
    [#text(weight: "bold", size: 8pt)[Flood Insurance] #v(1pt) #text(size: 9pt)[#{flood_insurance}]],
  )
]

#v(14pt)

// --- SECTION 4: RESERVE FUND ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 4 #h(8pt) Reserve Fund]
  ]
  #v(8pt)

  #grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 8pt,
    [#text(weight: "bold", size: 8pt)[Reserve Balance] #v(1pt) #text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9.5pt)[#{reserve_balance}]],
    [#text(weight: "bold", size: 8pt)[Percent Funded] #v(1pt) #text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9.5pt)[#{percent_funded}]],
    [#text(weight: "bold", size: 8pt)[Study Date] #v(1pt) #text(size: 9pt)[#{reserve_study_date}]],
  )
  #v(4pt)
  #grid(
    columns: (120pt, 1fr),
    [#text(weight: "bold", size: 8pt)[Annual Budget]], [#text(font: ("DejaVu Sans Mono", "Liberation Mono", "Courier New"), size: 9pt)[#{annual_budget}]],
  )
]

#v(14pt)

// --- SECTION 5: RESTRICTIONS & POLICIES ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 5 #h(8pt) Restrictions & Policies]
  ]
  #v(8pt)

  #grid(
    columns: (1fr, 1fr),
    row-gutter: 8pt,
    column-gutter: 16pt,
    [#text(weight: "bold", size: 8pt)[Rental Policy] #v(1pt) #text(size: 9pt)[#{rental_policy}]],
    [#text(weight: "bold", size: 8pt)[Short-Term Rental] #v(1pt) #text(size: 9pt)[#{short_term_rental_policy}]],
    [#text(weight: "bold", size: 8pt)[Pet Policy] #v(1pt) #text(size: 9pt)[#{pet_policy}]],
    [#text(weight: "bold", size: 8pt)[Parking] #v(1pt) #text(size: 9pt)[#{parking_policy}]],
    [#text(weight: "bold", size: 8pt)[Age Restrictions] #v(1pt) #text(size: 9pt)[#{age_restrictions}]],
    [#text(weight: "bold", size: 8pt)[Right of First Refusal] #v(1pt) #text(size: 9pt)[#{right_of_first_refusal}]],
  )
  #v(6pt)
  #text(weight: "bold", size: 8pt)[Unit-Specific Restrictions] #v(1pt)
  #text(size: 9pt)[#{unit_restrictions}]
]

#v(14pt)

// --- SECTION 6: LITIGATION ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: (x: 10pt, y: 6pt),
    fill: rgb("#1A1A2E"),
    radius: 2pt,
  )[
    #text(font: ("Liberation Sans", "DejaVu Sans", "Noto Sans"), size: 9pt, weight: "bold", fill: white)[Section 6 #h(8pt) Litigation Status]
  ]
  #v(8pt)

  #grid(
    columns: (120pt, 1fr),
    gutter: 6pt,
    [#text(weight: "bold", size: 9pt)[Pending Litigation:]], [#{in_litigation}],
    [#text(weight: "bold", size: 9pt)[Details:]], [#{litigation_details}],
  )
]

#v(18pt)

// --- CERTIFICATION ---
#block(breakable: false)[
  #rect(
    width: 100%,
    inset: 12pt,
    fill: rgb("#F0F7FF"),
    stroke: (left: 3pt + rgb("#38b6ff")),
    radius: 2pt,
  )[
    #text(size: 8.5pt, fill: rgb("#333"))[
      *CERTIFICATION:* This Resale Certificate is prepared in accordance with the Utah Community Association Act, Utah Code \u{00A7}57-8a-227. The information contained herein is believed to be accurate as of the date of preparation. This certificate is valid for thirty (30) days from the preparation date.

      #v(4pt)
      Pursuant to \u{00A7}57-8a-227(1)(b), Social Security numbers and bank account numbers have been redacted from this document.

      #v(4pt)
      This certificate does not constitute a guarantee or warranty of any kind. The recipient should conduct their own due diligence regarding the property and association.
    ]
  ]
]

#v(20pt)

// --- SIGNATURE ---
#block(breakable: false)[
  #grid(
    columns: (1fr, 1fr),
    gutter: 24pt,
    [
      #line(length: 85%, stroke: 0.5pt + rgb("#999"))
      #v(4pt)
      #text(size: 8pt, fill: rgb("#555"))[Prepared By: *#{prepared_by}*]
      #v(2pt)
      #text(size: 8pt, fill: rgb("#555"))[Date: #{preparation_date}]
    ],
    [
      #line(length: 85%, stroke: 0.5pt + rgb("#999"))
      #v(4pt)
      #text(size: 8pt, fill: rgb("#555"))[Title: *#{prepared_by_title}*]
      #v(2pt)
      #text(size: 8pt, fill: rgb("#555"))[Valid Through: #{valid_through}]
    ],
  )
]
